[Service]
Environment=XDG_DATA_DIRS=/home/marcelof/.local/share:/home/marcelof/.nix-profile/share:/home/marcelof/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
