git=github.com
worktree=1
mode=read

org=marcelofpfelix
branch=main
repo ansible-role-home
repo ansible-role-server
repo ansible-role-service

org=team-telnyx
branch=main
repo fone
repo tel-proxy-blackdog
repo kamadbg

branch=master

org=romkatv
repo zsh-defer

org=aloxaf
repo fzf-tab

org=zsh-users
repo zsh-autosuggestions
repo zsh-history-substring-search
repo zsh-syntax-highlighting
