git=github.com
worktree=1
mode=write

org=marcelofpfelix
branch=main
repo dotfiles
repo homework
repo wiki
repo ansible-role-home worktree=1 mode=read
repo ansible-role-server worktree=1 mode=read
repo ansible-role-service worktree=1 mode=read

org=team-telnyx
branch=marcelo
repo tel-proxy
repo fone branch=main worktree=1 mode=read
repo tel-proxy-blackdog branch=main worktree=1 mode=read
repo kamadbg branch=main worktree=1 mode=read

mode=read
branch=master

org=romkatv
repo zsh-defer

org=aloxaf
repo fzf-tab

org=zsh-users
repo zsh-autosuggestions
repo zsh-history-substring-search
repo zsh-syntax-highlighting
