# See https://pre-ommit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
    -   id: gitleaks
-   repo: local
    hooks:
    -   id: check-bin-executables
        name: check bin executable bits
        entry: default/bin/check-bin-executables
        language: system
        pass_filenames: false
    -   id: act-ci
        name: run GitHub Actions locally with act
        entry: act -W .github/workflows/ci.yml
        language: system
        pass_filenames: false
        stages: [manual]
