[desktop]
localhost
laptop

[nuc]
pve

[hc4]
glr

[mac]
mac

[laptop]
laptop

[pvm]
pvm01
pvm02
pvm03
pve-sre

[blab:children]
nuc
pvm
hc4
mac
laptop

#[hc4:vars]
#ansible_ssh_common_args='-F /home/marcelof/.ssh/config'
