---
collections:
  - name: git+https://github.com/marcelofpfelix/ansible-collection-homelab.git
    type: git
    version: c80213fac9adca37eddb5020f9c1f765d3167c1e

  - name: community.docker
    version: 4.8.5
  - name: geerlingguy.mac
    version: 5.0.0
  - name: community.general
    version: 10.7.6
