extra-keys = [['ESC','TAB','CTRL','ALT','-','/','HOME','END'],['~','|','`','$','UP','PGUP','BKSP','DEL'],['KEYBOARD','LEFT','DOWN','RIGHT','PGDN',';','"','ENTER']]
terminal-cursor-style = bar
terminal-transcript-rows = 50000
bell-character = ignore
use-black-ui = true
